version: "3"
services:
  rabbitmq:
    image: "rabbitmq:3-management-alpine"
    container_name: fraud-detection-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /fraud-detection
    ports:
      - "5672:5672"
      - "15672:15672"
